require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/customers", type: :request do
  let(:organization) { create(:organization) }
  let(:customer) { create(:customer, organization: organization) }
  let(:user) { create(:user, organization: organization, password: 'password') }

  before do
    sign_in(user)
  end

  let(:valid_attributes) {
    {
      name: "Test Customer",
      email: "test@example.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
      organization_id: organization.id,
      company_name: "Test Company"
    }
  }

  let(:invalid_attributes) {
    {
      name: "",
      email: "invalid-email",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
      organization_id: organization.id,
      company_name: "Test Company"
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Customer.create! valid_attributes
      get customers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get customer_url(customer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_customer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      get edit_customer_path(customer), headers: { "Turbo-Frame" => "modal" }
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Customer" do
        expect {
          post customers_url, params: { customer: valid_attributes }
        }.to change(Customer, :count).by(1)
      end

      it "redirects to the created customer" do
        post customers_url, params: { customer: valid_attributes }
        expect(response).to redirect_to(customers_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Customer" do
        expect {
          post customers_url, params: { customer: invalid_attributes }
        }.to change(Customer, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post customers_url, params: { customer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      it "updates the requested customer" do
        patch customer_path(customer), params: { customer: FactoryBot.attributes_for(:customer) }
        expect(response).to redirect_to(customers_url)
        expect(flash[:notice]).to eq 'Customer was successfully updated.'
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch customer_url(customer), params: { customer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested customer" do
      customer_id = customer.id
      expect {
        delete customer_url(customer)
      }.to change(Customer, :count).by(-1)
    end

    it "redirects to the customers list" do
      delete customer_url(customer)
      expect(response).to redirect_to(customers_url)
    end
  end
end
