require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stock_movements", type: :request do
  let(:organization) { create(:organization) }
  let(:user) { create(:user, organization: organization, password: 'password') }
  let(:product) { create(:product, organization: organization) }
  let(:warehouse) { create(:warehouse, organization: organization) }
  let(:stock_movement) { create(:stock_movement, organization: organization, user: user, product: product, warehouse: warehouse) }

  before do
    sign_in(user)
  end

  let(:valid_attributes) {
    {
      organization_id: organization.id,
      user_id: user.id,
      product_id: product.id,
      warehouse_id: warehouse.id,
      quantity_change: 10,
      movement_date: Date.today,
      notes: "Test notes",
      movement_type: :initial
    }
  }

  let(:invalid_attributes) {
    {
      organization_id: nil,
      user_id: nil,
      product_id: nil,
      warehouse_id: nil,
      quantity_change: nil,
      movement_date: nil,
      notes: nil,
      movement_type: nil
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      StockMovement.create! valid_attributes
      get stock_movements_url
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stock_movement_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StockMovement" do
        expect {
          post stock_movements_url, params: { stock_movement: valid_attributes }
        }.to change(StockMovement, :count).by(1)
      end

      it "redirects to the created stock_movement" do
        post stock_movements_url, params: { stock_movement: valid_attributes }
        expect(response).to redirect_to(stock_movements_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new StockMovement" do
        expect {
          post stock_movements_url, params: { stock_movement: invalid_attributes }
        }.to change(StockMovement, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post stock_movements_url, params: { stock_movement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end
end
