require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/suppliers", type: :request do
  let(:organization) { create(:organization) }
  let(:user) { create(:user, organization: organization, password: 'password') }
  let(:supplier) { create(:supplier, organization: organization) }


  before do
    sign_in(user)
  end

  let(:valid_attributes) {
    {
      company_name: "Test Company",
      supplier_name: "Test Supplier",
      supplier_email: "test@example.com",
      supplier_phone: "1234567890",
      supplier_address: "123 Main St, Anytown, USA",
      notes: "Test notes",
      organization_id: organization.id
    }
  }

  let(:invalid_attributes) {
    {
      company_name: nil,
      supplier_name: nil,
      supplier_email: nil,
      supplier_phone: nil,
      supplier_address: nil,
      notes: nil,
      organization_id: nil
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Supplier.create! valid_attributes
      get suppliers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      supplier = Supplier.create! valid_attributes
      get supplier_url(supplier)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_supplier_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      supplier = Supplier.create! valid_attributes
      get edit_supplier_url(supplier)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Supplier" do
        expect {
          post suppliers_url, params: { supplier: valid_attributes }
        }.to change(Supplier, :count).by(1)
      end

      it "redirects to the created supplier" do
        post suppliers_url, params: { supplier: valid_attributes }
        expect(response).to redirect_to(suppliers_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Supplier" do
        expect {
          post suppliers_url, params: { supplier: invalid_attributes }
        }.to change(Supplier, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post suppliers_url, params: { supplier: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          company_name: "Updated Company",
          supplier_name: "Updated Supplier",
          supplier_email: "updated@example.com",
          supplier_phone: "9876543210",
          supplier_address: "456 Main St, Anytown, USA",
          notes: "Updated notes",
          organization_id: organization.id
        }
      }

      it "updates the requested supplier" do
        supplier = Supplier.create! valid_attributes
        patch supplier_url(supplier), params: { supplier: new_attributes }
        supplier.reload
        expect(supplier.company_name).to eq("Updated Company")
        expect(supplier.supplier_name).to eq("Updated Supplier")
        expect(supplier.supplier_email).to eq("updated@example.com")
        expect(supplier.supplier_phone).to eq("9876543210")
        expect(supplier.supplier_address).to eq("456 Main St, Anytown, USA")
        expect(supplier.notes).to eq("Updated notes")
        expect(supplier.organization_id).to eq(organization.id)
      end

      it "redirects to the supplier" do
        supplier = Supplier.create! valid_attributes
        patch supplier_url(supplier), params: { supplier: new_attributes }
        supplier.reload
        expect(response).to redirect_to(supplier_url(supplier))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        supplier = Supplier.create! valid_attributes
        patch supplier_url(supplier), params: { supplier: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested supplier" do
      supplier = Supplier.create! valid_attributes
      expect {
        delete supplier_url(supplier)
      }.to change(Supplier, :count).by(-1)
    end

    it "redirects to the suppliers list" do
      supplier = Supplier.create! valid_attributes
      delete supplier_url(supplier)
      expect(response).to redirect_to(suppliers_url)
    end
  end
end
