require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/warehouses", type: :request do
  let(:organization) { create(:organization) }
  let(:user) { create(:user, organization: organization, password: 'password') }

  before do
    sign_in(user)
  end

  let(:valid_attributes) {
    {
      name: "Test Warehouse",
      address: "123 Main St, Anytown, USA",
      capacity: 100,
      organization_id: organization.id
    }
  }

  let(:invalid_attributes) {
    {
      name: nil,
      address: nil,
      capacity: nil,
      organization_id: nil
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Warehouse.create! valid_attributes
      get warehouses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      warehouse = Warehouse.create! valid_attributes
      get warehouse_url(warehouse)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_warehouse_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      warehouse = Warehouse.create! valid_attributes
      get edit_warehouse_url(warehouse)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Warehouse" do
        expect {
          post warehouses_url, params: { warehouse: valid_attributes }
        }.to change(Warehouse, :count).by(1)
      end

      it "redirects to the created warehouse" do
        post warehouses_url, params: { warehouse: valid_attributes }
        expect(response).to redirect_to(warehouses_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Warehouse" do
        expect {
          post warehouses_url, params: { warehouse: invalid_attributes }
        }.to change(Warehouse, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post warehouses_url, params: { warehouse: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "Updated Warehouse",
          address: "456 Main St, Anytown, USA",
          capacity: 200,
          organization_id: organization.id
        }
      }

      it "updates the requested warehouse" do
        warehouse = Warehouse.create! valid_attributes
        patch warehouse_url(warehouse), params: { warehouse: new_attributes }
        warehouse.reload
        expect(warehouse.name).to eq("Updated Warehouse")
        expect(warehouse.address).to eq("456 Main St, Anytown, USA")
        expect(warehouse.capacity).to eq(200)
        expect(warehouse.organization_id).to eq(organization.id)
      end

      it "redirects to the warehouse" do
        warehouse = Warehouse.create! valid_attributes
        patch warehouse_url(warehouse), params: { warehouse: new_attributes }
        warehouse.reload
        expect(response).to redirect_to(warehouse_url(warehouse))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        warehouse = Warehouse.create! valid_attributes
        patch warehouse_url(warehouse), params: { warehouse: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested warehouse" do
      warehouse = Warehouse.create! valid_attributes
      expect {
        delete warehouse_url(warehouse)
      }.to change(Warehouse, :count).by(-1)
    end

    it "redirects to the warehouses list" do
      warehouse = Warehouse.create! valid_attributes
      delete warehouse_url(warehouse)
      expect(response).to redirect_to(warehouses_url)
    end
  end
end
